name: Opsgenie Maintenance Mode

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  maintenance_mode:
    runs-on: ubuntu-latest
    steps:
      - name: Disable CloudWatch Integration in Opsgenie
        run: |
          curl -X PUT "https://api.opsgenie.com/v2/integrations/${{ secrets.CLOUDWATCH_INTEGRATION_ID }}/disable" \
          -H "Authorization: GenieKey ${{ secrets.OPSGENIE_API_KEY }}" \
          -H "Content-Type: application/json"


