name: Enable Opsgenie Maintenance Mode for Test Integration

on:
  workflow_dispatch: # Allows manual trigger from GitHub Actions

jobs:
  enable-maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Start Maintenance Mode (5 min)
        run: |
          START_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          END_TIME=$(date -u -d "+5 minutes" +"%Y-%m-%dT%H:%M:%SZ")
          
          curl -X POST "https://api.opsgenie.com/v1/maintenance" \
          -H "Authorization: GenieKey ${{ secrets.OPSGENIE_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "description": "GitHub Action triggered maintenance for Test Integration",
            "startDate": "'"$START_TIME"'",
            "endDate": "'"$END_TIME"'",
            "integrationId": "${{ secrets.OPSGENIE_INTEGRATION_ID }}"
          }'

      - name: Confirm Maintenance Mode
        run: |
          curl -X GET "https://api.opsgenie.com/v1/maintenance" \
          -H "Authorization: GenieKey ${{ secrets.OPSGENIE_API_KEY }}"
          
      - name: Wait for 5 Minutes
        run: sleep 300

      - name: Stop Maintenance Mode
        run: |
          curl -X DELETE "https://api.opsgenie.com/v1/maintenance" \
          -H "Authorization: GenieKey ${{ secrets.OPSGENIE_API_KEY }}"
