name: Opsgenie Maintenance Mode

on:
  workflow_dispatch:  # Manual trigger

jobs:
  maintenance_mode:
    runs-on: ubuntu-latest
    steps:
      - name: Disable CloudWatch Integration in Opsgenie
        run: |
          curl -X PATCH "https://api.opsgenie.com/v2/integrations/<CLOUDWATCH_INTEGRATION_ID>" \
          -H "Authorization: GenieKey ${{ secrets.OPSGENIE_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"enabled": false}'
        env:
          CLOUDWATCH_INTEGRATION_ID: "17a38b3f-d83b-4db4-b3bc-44bf49f9650b"


