name: Opsgenie Maintenance Mode

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  maintenance_mode:
    runs-on: ubuntu-latest
    steps:
      - name: Start Maintenance Mode in Opsgenie
        id: start_maintenance
        run: |
          RESPONSE=$(curl -s -X POST "https://api.opsgenie.com/v1/maintenance" \
            -H "Authorization: GenieKey ${{ secrets.OPSGENIE_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "description": "Scheduled maintenance to disable CloudWatch integration",
              "time": {"type": "minutes", "value": 5},
              "services": ["CloudWatch"]
            }')
          MAINTENANCE_ID=$(echo $RESPONSE | jq -r '.data.id')
          echo "MAINTENANCE_ID=$MAINTENANCE_ID" >> $GITHUB_ENV

